name: Update AtCoder Data

on:
  push:                #自分がPushした瞬間に動く
    branches:
      - main
  schedule:
    # 5分おきにチェック（これなら「解いたらすぐ」に近い感覚になります！）
    - cron: '*/5 * * * *' 
  workflow_dispatch:      # 手動でも実行できるボタン

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # ★ファイルを書き換える許可

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python AtCoder/get_ac.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add AtCoder/atcoder_data.json
          # 変更がある場合のみコミットして保存（Push）する
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update AtCoder data" && git push)